/*
  bcn_management.js
  Language: cz-cz
*/
define({
    "STR_BUSINESS_GOALS": "Obchodní cíle",
    "STR_OVERALL_GOALS_VIEW": "Zobrazit celkový přehled cílů",
    "STR_RETURN_TO_MANAGER_VIEW": "Návrat k zobrazení Manager",
    "STR_ADD_A_NEW_GOAL": "Přidat nový cíl",
    "STR_LOADING_GOALS": "Načítám cíle......",
    "STR_BUSINESS_GOALS_HELP": "Nápověda Obchodní cíle",
    "STR_BUSINESS_GOALS_WIDGET_WAS_CREATED": "Ovládací prvek Obchodní cíle byl vytvořen, aby pomáhal manažerovi organizovat obchodní cíle. V tomto ovládacím prvku může manažer definovat cíle, upravovat, mazat a přidávat vzdělávací indikátory, přiřazovat priority k jednotlivým cílům.",
    "STR_TO_ADD_NEW_BUSINESS_GOAL_CLICK": "K přidání nového podniku klikněte na<button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-plus\"></span></button> ikonu. V novém okně napište<em>Název</em>, <em>Popis</em> a vyberte<em>Priorita</em> pro váš cíl. K přidání nového<em>vzdělávacího indikátoru</em> klikněte na<button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-flag\" style=\"margin-right:5px;\"></span><span class=\"glyphicon glyphicon-plus\"></span></button> ikonu.",
    "STR_TO_SEE_OVERALL_PROGRESS_OF_ALL": "K zobrazení celkového pokroku všech zaměstnanců klikněte na<button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> ikonu. Zobrazí se graf v ovládacím prvku Vzdělávací pokrok.",
    "STR_TO_EDIT_GOAL_CLICK_ON_ICON": "K upravení cíle klikněte na <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-edit\"></span></button> ikonu.",
    "STR_TO_DELETE_GOAL_CLICK_ON_ICON": "K vymazání cíle klikněte na <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-trash\"></span></button> ikonu.",
    "STR_TO_MONITOR_THE_LEARNING_PROGRESS": "K monitorování vzdělávacího pokroku každého zaměstnance přímo v <em>Vzdělávací pokrok</em> ovládacím prvku klikněte na <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> ikonu.",
    "STR_IN_THIS_WIDGET_YOU_CAN_MONITOR": "V tomto ovládacím prvku můžete monitorovat přiřazené cíle a časové osy. Klikněte na <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> ikonu k zobrazení pokroku u tohoto cíle v ovládacím prvku Vzdělávací pokrok.",
    "STR_SHOW_OPTIONS": "Zobrazit možnosti",
    "STR_EDIT": "Upravit:",
    "STR_DELETE_COLONS": "Vymazat:",
    "STR_SHOW_PROGRESS": "Zobrazit pokrok:",
    "STR_DAYS_BEFORE_THE_DEADLINE": "Dnů před konečným termínem:",
    "STR_20_COMPLETE": "20% Dokončeno",
    "STR_DESCRIPTION": "Popis",
    "STR_PRIORITY": "Priorita",
    "STR_LEARNING_INDICATORS": "Vzdělávací indikátory",
    "STR_SAVE": "Uložit",
    "STR_EDIT_GOAL": "Upravit cíl",
    "STR_DO_YOU_REALLY_WANT_TO_DELETE": "Opravdu chcete vymazat?",
    "STR_CANCEL": "Zrušit",
    "STR_DELETE": "Smazat",
    "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Litujeme, licence pro BOOST nebyla akceptována",
    "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Předtím, než budete pokračovat, nejprve musíte  spustit BOOST uvítací ovládací prvek (BOOST Welcome Widget) a souhlasit s licenčními podmínkami konečného uživatele",
    "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Litujeme, nemáte práva přístupu k tomuto ovládacímu prvku ",
    "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Předtím, než budete pokračovat, prosím kontaktujte svého manažera nebo správce",
    "STR_SHOW_HELP": "Ukaž nápovědu",
    "STR_YOU_HAVE_NO_ROLE": "Nyní máte <strong>ŽÁDNÁ</strong> role. Prosím, kontaktujte manažera k přidělení vašich rolí",
    "STR_CLOSE": "Zavřít",
    "STR_SHOW_PROGRESS": "Zobrazit pokrok:",
    "STR_NAME": "Název",
    "STR_WIDTH": "šíře",
    "STR_ENTER_NAME": "Vložte jméno",
    "STR_ENTER_DESCRIPTION": "Vložte popis",
    "STR_ENTER_LI_NAME": "Vložte název vzdělávacího indikátoru"
});
