/*
  employee.js
  Language: cz-cz
*/
define({
    "STR_BUSINESS_EMPLOYEES": "Zaměstnanci podniku",
    "STR_MANAGE_YOUR_EMPLOYEES_AND_ASSIGN": "Organizujte své zaměstnance a přiřazujte jim vzdělávací cíle.",
    "STR_PLEASE_WAIT_WHILE_THE_EMPLOYEES": "Prosím čekejte než se zaměstnanci zaktualizují, aby se projevily tyto změny.",
    "STR_OVERALL_EMPLOYEE_VIEW": "Celkový přehled zaměstnanců",
    "STR_LOADING_EMPLOYEE_DATA": "Načítám data zaměstnanců........",
    "STR_ASSIGN_GOALS": "Přiřadit cíle:",
    "STR_SEND_EMAIL": "Poslat email:",
    "STR_SHOW_DEADLINES": "Zobrazit konečné termíny:",
    "STR_NAME_MUST_NOT_BE_EMPTY": "Jméno nesmí zůstat prázdné.",
    "STR_EMAIL": "Email",
    "STR_ENTER_EMAIL": "Napište email",
    "STR_PLEASE_ENTER_A_VALID_EMAIL_ADRESS": "Prosím napište platnou emailovou adresu.",
    "STR_VIEW/UPDATE_EMPLOYEE": "Zobrazit/Aktualizovat zaměstnance",
    "STR_ADD_NEW_EMPLOYEE": "Přidat nového zaměstnance",
    "STR_RELEVANT": "Relevantní",
    "STR_START_DATE": "Datum začátku",
    "STR_END_DATE": "Datum konce",
    "STR_START_LEVEL": "Počáteční úroveň:",
    "STR_CURRENT_LEVEL": "Současná úroveň:",
    "STR_END_LEVEL": "Konečná úroveň:",
    "STR_DO_YOU_WANT_TO_DELETE_EMPLOYEE": "Opravdu chcete vymazat zaměstnance {{zaměstnanec. Jméno}}?",
    "STR_BUSINESS_EMPLOYEES_HELP": "Nápověda Zaměstnanci podniku",
    "STR_IN_THE_BUSINESS_EMPLOYEES_WIDGET": "V ovládacím prvku Zaměstnanci podniku můžete přiřazovat cíle zaměstnancům, upravovat jejich vzdělávací úrovně a specifikovat konečné termíny.",
    "STR_TO_SEE_MORE_OPTIONS_CLICK_ON": "K zobrazení více možností klikněte na <button type=\"button\" class=\"btn btn-default btn-sm dropdown-toggle\"><i class=\"fa fa-cogs\"></em><span class=\"caret\"></span></button> ikonu.",
    "STR_TO_ASSIGN_GOALS_TO_EMPLOYEE_AND": "K přiřazení cílů zaměstnanci a stanovení vzdělávacích úrovní klikněte na <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-flag\" style=\"margin-right:5px;\"></span></button> ikonu. V novém okně zapište relevantní cíle pro tohoto zaměstnance.",
    "STR_CHECK_IN_RELEVANT_LEARNING_INDICATORS": "Zkontrolujte relevantní indikátory a definujte vzdělávací úrovně pro tohoto zaměstnance kliknutím na název cíle a výběrem položky Počáteční, Současná a Konečná úroveň odpovídajícím způsobem.",
    "STR_CHOOSE_START_AND_END_DATES_FOR": "Zvolte data začátku a konce pro vzdělávací indikátory.",
    "STR_DESCRIPTIONS_OF_LEARNING_LEVELS": "Popisy vzdělávacích úrovní:",
    "STR_LEVEL_0_I_HAVE_NOT_STARTED_TO": "<li><strong>Úroveň 0:</strong> Nezačal/a jsem pracovat na dovednostech / vědomostech potřebných k tomuto indikátoru. </li><li><strong>Úroveň 1:</strong> Začal/a jsem zkoušet řešit dovednosti / vědomosti potřebné k tomuto indikátoru, ale potřebuji více času / podpory abych pokročil/a. </li><li><strong>Úroveň 2:</strong> Cítím, že jsem získal/a některé dovednosti / vědomosti a jsem si vědom/a pokroku, který jsem udělal/a vzhledem k tomuto indikátoru, ale cítím, že se potřebuji naučit více předtím, než je začnu v práci reálně používat. </li><li><strong>Úroveň 3:</strong> Mám pocit, že jsem získal/a významné dovednosti / vědomosti pro mou současnou pracovní pozici a začal/a jsem je používat v praxi. </li><li><strong>Úroveň 4:</strong> Mám pocit, že jsem získal/a významné znalosti ohledně těchto dovedností pro mou současnou práci, ale pro budoucí rozvoj v rámci společnosti, uznávám, že se mohu dál rozvíjet.</li><li><strong>Úroveň 5:</strong> Cítím se dostatečně sebevědomý v používání těchto dovedností a vědomostí, že bych mohl ohledně těchto dovedností podpořit několik kolegů?</li>",
    "STR_TO_MONITOR_THE_LEARNING_EMPLOYEE": "K monitorování vzdělávacího pokroku zaměstnance jděte na <em>Vzdělávací pokrok</em> ovládací prvek, klikněte na <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats tooltip-showGoalProgress\" data-placement=\"left\" data-toggle=\"tooltip\" data-original-title=\"Show Progress: Decor and Furnishing\"></span></button> ikonu.",
    "STR_TO_SEND_EMAIL_TO_THE_EMPLOYEES": "K poslání emailu zaměstnancům klikněte na <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-envelope\" style=\"margin-right:5px;\"></span></button> ikonu. Objeví se mailové vyskakovací okno.",
    "STR_IN_THIS_WIDGET_YOU_CAN_SEE_YOUR": "V tomto ovládacím prvku můžete vidět detaily vašeho profilu. Klikněte na <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> ikonu k zobrazení celkového pokroku v ovládacím prvku Vzdělávací pokrok.",
    "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Litujeme, licence pro BOOST nebyla akceptována",
    "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Předtím, než budete pokračovat, nejprve musíte  spustit BOOST uvítací ovládací prvek (BOOST Welcome Widget) a souhlasit s licenčními podmínkami konečného uživatele",
    "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Litujeme, nemáte práva přístupu k tomuto ovládacímu prvku ",
    "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Předtím, než budete pokračovat, prosím kontaktujte svého manažera nebo správce",
    "STR_CLOSE": "Zavřít",
    "STR_SHOW_HELP": "Ukaž nápovědu",
    "STR_SHOW_PROGRESS": "Zobrazit pokrok:",
    "STR_YOU_HAVE_NO_ROLE": "Nyní máte <strong>ŽÁDNÁ</strong> role. Prosím, kontaktujte manažera k přidělení vašich rolí",
    "STR_SHOW_OPTIONS": "Zobrazit možnosti",
    "STR_SHOW_PROGRESS": "Zobrazit pokrok:",
    "STR_SAVE": "Uložit",
    "STR_CANCEL": "Zrušit",
    "STR_DELETE": "Smazat"
});
