/*
  bcn_management.js
  Language: de-de
*/
define({
    "STR_BUSINESS_GOALS": "Unternehmensziele",
    "STR_OVERALL_GOALS_VIEW": "Gesamte Ziele Anzeige",
    "STR_RETURN_TO_MANAGER_VIEW": "Zurück zur Manager Ansicht",
    "STR_ADD_A_NEW_GOAL": "Fügen Sie ein neues Ziel hinzu",
    "STR_LOADING_GOALS": "Lade Ziele ...",
    "STR_BUSINESS_GOALS_HELP": "Unternehmensziele Hilfe",
    "STR_BUSINESS_GOALS_WIDGET_WAS_CREATED": "Das unternehmensziele Widget wurde entwickelt, um Manager zu helfen Unternehmensziele zu organisieren. In diesem Widget kann der Manager Ziele definieren, bearbeiten, löschen, Lern Indikatoren hinzufügen und Zielen Prioritäten zuweisen.",
    "STR_TO_ADD_NEW_BUSINESS_GOAL_CLICK": "Um ein neues Geschäftsziel hinzufügen Klicken Sie auf <button type = \"button\" class = \"btn btn-Primär btn-sm\"> <span class = \"glyphicon glyphicon-plus\"> </ span> </ button> Icon. In der neuen Ansicht eingeben <em> Name </ em>, <em> Beschreibung </ em> und wählen Sie <em> Priorität </ em> für Ihr Ziel. So fügen Sie neue <em> Lernen Indikator </ em> auf <Button type = \"button\" class = \"btn btn-Primär btn-sm\"> <span class = \"glyphicon glyphicon-flag\" style = \"margin-right: 5px; \"> </ span> <span class =\" glyphicon glyphicon-plus \"> </ span> </ button> Icon.",
    "STR_TO_SEE_OVERALL_PROGRESS_OF_ALL": "Um den Gesamtfortschritt aller Mitarbeiter zu sehen klicken Sie auf <button type = \"button\" class = \"btn btn-Primär btn-sm\"> <span class = \"glyphicon glyphicon-stats\"> </ span> </ button>das Icon. Der Graph wird im Lernfortschritt Widget angezeigt.",
    "STR_TO_EDIT_GOAL_CLICK_ON_ICON": "Um das Ziel zu Bearbeiten, klicken Sie auf <button class = \"btn btn-default btn-sm\"> <span class = \"glyphicon glyphicon-edit\"> </ span> </ button>das Icon.",
    "STR_TO_DELETE_GOAL_CLICK_ON_ICON": "Um das Ziel zu Löschen klicken Sie auf <class = \"btn btn-default btn-sm\"> <span class = \"glyphicon glyphicon-Trash\"> </ span> </ button>das Icon.",
    "STR_TO_MONITOR_THE_LEARNING_PROGRESS": "Um den Lernfortschritt jedes einzelnen Mitarbeiters direkt im <em> Lernfortschritt </ em>-Widget zu beobachten, klicken Sie auf <button class = \"btn btn-default btn-sm\"> <span class = \"glyphicon glyphicon-stats\"> </ Spannweite / button>das Icon.",
    "STR_IN_THIS_WIDGET_YOU_CAN_MONITOR": "In diesem Widget können Sie die zugewiesenen Ziele und den Zeitrahmen beobachten. Klicken Sie auf <button class = \"btn btn-default btn-sm\"> <span class = \"glyphicon glyphicon-stats\"> </ span> </ button> das Icon, um Fortschritte im Laufe dieses Ziel in dem Lernfortschritt Widget zu sehen.",
    "STR_SHOW_OPTIONS": "Optionen anzeigen",
    "STR_EDIT": "Bearbeiten:",
    "STR_DELETE_COLONS": "Löschen:",
    "STR_SHOW_PROGRESS": "Fortschritt anzeigen:",
    "STR_DAYS_BEFORE_THE_DEADLINE": "Tage bis zum Zieltermin:",
    "STR_20_COMPLETE": "20% abgeschlossen",
    "STR_DESCRIPTION": "Beschreibung",
    "STR_PRIORITY": "Priorität",
    "STR_LEARNING_INDICATORS": "Lern Indikatoren",
    "STR_SAVE": "Speichern",
    "STR_EDIT_GOAL": "Ziel ändern",
    "STR_DO_YOU_REALLY_WANT_TO_DELETE": "Wollen Sie wirklich löschen ?",
    "STR_CANCEL": "Abbrechen",
    "STR_DELETE": "Löschen",
    "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Sorry, die Lizenz für BOOST wurde nicht akzeptiert",
    "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Bevor Sie fortfahren müssen Sie zuerst das BOOST Willkommen Widget starten und die Endbenutzer-Lizenzvereinbarung akzeptieren.",
    "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Sorry, Sie haben keine Rechte auf dieses Widget zugreifen",
    "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Bitte kontaktieren Sie Ihre Manager oder Administrator bevor Sie fortfahren",
    "STR_SHOW_HELP": "Hilfe anzeigen",
    "STR_YOU_HAVE_NO_ROLE": "Sie haben <strong> keine </strong> Rolle. Bitte kontaktieren Sie ihre Manager um von ihm eine Rolle zugewisen zu bekommen",
    "STR_CLOSE": "Schließen",
    "STR_SHOW_PROGRESS": "Fortschritt anzeigen:",
    "STR_NAME": "Name",
    "STR_WIDTH": "Breite:",
    "STR_ENTER_NAME": "Name eingeben",
    "STR_ENTER_DESCRIPTION": "Beschreibung eingeben",
    "STR_ENTER_LI_NAME": "Name des Lernindikators eingeben"
});
