/*
  employee.js
  Language: de-de
*/
define({
    "STR_BUSINESS_EMPLOYEES": "Firmen Mitarbeiter",
    "STR_MANAGE_YOUR_EMPLOYEES_AND_ASSIGN": "Verwalten Sie Ihre Mitarbeiter und weisen ihnen Lernziele zu.",
    "STR_PLEASE_WAIT_WHILE_THE_EMPLOYEES": "Bitte warten Sie, während die Mitarbeiter aktualisiert werden, um diese Änderungen anzuzeigen.",
    "STR_OVERALL_EMPLOYEE_VIEW": "Gesamt Mitarbeiter Ansicht",
    "STR_LOADING_EMPLOYEE_DATA": "Laden Mitarbeiterdaten ...",
    "STR_ASSIGN_GOALS": "Ziele vergeben :",
    "STR_SEND_EMAIL": "E-Mail senden:",
    "STR_SHOW_DEADLINES": "Zeige Zieletermine:",
    "STR_NAME_MUST_NOT_BE_EMPTY": "Name darf nicht leer sein.",
    "STR_EMAIL": "E-Mail",
    "STR_ENTER_EMAIL": "Geben Sie die Email- Adresse ein",
    "STR_PLEASE_ENTER_A_VALID_EMAIL_ADRESS": "Bitte geben Sie eine gültige Email-Adresse.",
    "STR_VIEW/UPDATE_EMPLOYEE": "Ansicht / Update Mitarbeiter",
    "STR_ADD_NEW_EMPLOYEE": "Hinzufügen neuer Mitarbeiter",
    "STR_RELEVANT": "Relevante",
    "STR_START_DATE": "Startdatum",
    "STR_END_DATE": "Enddatum",
    "STR_START_LEVEL": "Start Level :",
    "STR_CURRENT_LEVEL": "Aktuell Level :",
    "STR_END_LEVEL": "End Level :",
    "STR_DO_YOU_WANT_TO_DELETE_EMPLOYEE": "Wollen Sie wirklich {{employee.name}}  als Angestellten löschen?",
    "STR_BUSINESS_EMPLOYEES_HELP": "Business Mitarbeiter Hilfe",
    "STR_IN_THE_BUSINESS_EMPLOYEES_WIDGET": "Im Business Mitarbeiter-Widget können Sie Ziele für die Mitarbeiter zuordnen, ihre Lernstufen einstellen und Fristen für sie vergeben.",
    "STR_TO_SEE_MORE_OPTIONS_CLICK_ON": "Um weitere Optionen zu sehen klicken Sie auf <button type = \"button\" class = \"btn btn-default btn-sm dropdown-toggle\"> <i class = \"fa fa-cogs\"> </em> <span class = \"caret\" > </ span> </ button> das Icon.",
    "STR_TO_ASSIGN_GOALS_TO_EMPLOYEE_AND": "Um Ziele und Lernstufen für die Mitarbeiter zu vergeben klicken Sie auf <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-flag\" style=\"margin-right:5px;\"></span></button>das Icon. Check-in Sie  in der neuen Ansicht die relevanten Ziele für diese Mitarbeiter.",
    "STR_CHECK_IN_RELEVANT_LEARNING_INDICATORS": "Wählen Sie die relevanten Lernindikatoren aus und definieren Sie Lernstufen für diesen Mitarbeiter, indem Sie auf den Zielnamen klicken und wählen Sie das Start, Aktuelle und End Level entsprechend.",
    "STR_CHOOSE_START_AND_END_DATES_FOR": "Wählen Sie das Start- und Enddatum für die Lernindikatoren.",
    "STR_DESCRIPTIONS_OF_LEARNING_LEVELS": "Beschreibungen von Lernstufen :",
    "STR_LEVEL_0_I_HAVE_NOT_STARTED_TO": "<li> <strong> Level 0: </ strong> Ich habe nicht damit begonnen, die Fähigkeiten / Kenntnisse für diesen Indikator benötigt zu sammeln.</ li> <li> <strong> Level 1:</ strong> Ich habe angefangen zu versuchen die Fähigkeiten / Kenntnisse für diesen Indikator anzueignen, brauche aber mehr Zeit / Unterstützung um Fortschritte zu machen. </ li> <li> <strong> Level 2: </ strong> Ich habe das Gefühl, dass ich einige Fähigkeiten / Kenntnisse bezüglich des Indikatores erworben habe und bin mir aber bewusst das ich mehr Lernen muss bevor ich das Gelernte bei der Arbeit in die Praxis umzusetzen kann. </ li> <li> <strong> Level 3: </ strong> Ich habe das Gefühl, dass ich beachtliche Fähigkeiten / Kenntnisse für meinen aktuellen Job Rolle erworben habe und damit begonnen das Gelernte bei der Arbeit in die Praxis umzusetzen. </ li> <li> <strong> Level 4:. </ strong> Ich habe das Gefühl, dass ich beachtliche Kenntnisse dieser Fähigkeit für meine aktuelle Tätigkeit erworben habe. Ich erkenne, das ich für die zukünftige Entwicklung im Unternehmen die Fähigkeiten weiterentwickeln kann. </ li> <li> <strong> Level 5: </ strong> Ich fühle mich bei der Anwendung dieser Fähigkeiten und Kenntnisse sicher genug, um ein paar Kollegen in Bezug auf diese zu unterstützen. </ li>",
    "STR_TO_MONITOR_THE_LEARNING_EMPLOYEE": "Um die Lernfortschritte der Mitarbeiter direkt im <em>Learning Progress</em> Widget zu sehen klicken Sie auf <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats tooltip-showGoalProgress\" data-placement=\"left\" data-toggle=\"tooltip\" data-original-title=\"Status anzeigen : Dekoration und Einrichtung\"></span></button>das Icon.",
    "STR_TO_SEND_EMAIL_TO_THE_EMPLOYEES": "Um eine E-Mail an die Mitarbeiter zu senden klicken Sie auf <button class = \"btn btn btn-default-sm\"> <span class = \"glyphicon glyphicon-envelope\" style = \"margin-right: 5px;\"> </ span> </ button > das Icon. Das Pop-up-Mail-Fenster wird angezeigt.",
    "STR_IN_THIS_WIDGET_YOU_CAN_SEE_YOUR": "In diesem Widget können Sie die Profildetails sehen. Klicken Sie auf <class = \"btn btn btn-default-sm\"> <span class = \"glyphicon glyphicon-stats\"> </ span> </ button> das Icon, um den Gesamtfortschritt im Lernfortschritt Widget zu sehen.",
    "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Sorry, die Lizenz für BOOST wurde nicht akzeptiert",
    "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Bevor Sie fortfahren müssen Sie zuerst das BOOST Willkommen Widget starten und die Endbenutzer-Lizenzvereinbarung akzeptieren.",
    "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Sorry, Sie haben keine Rechte auf dieses Widget zugreifen",
    "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Bitte kontaktieren Sie Ihre Manager oder Administrator bevor Sie fortfahren",
    "STR_CLOSE": "Schließen",
    "STR_SHOW_HELP": "Hilfe anzeigen",
    "STR_SHOW_PROGRESS": "Fortschritt anzeigen:",
    "STR_YOU_HAVE_NO_ROLE": "Sie haben <strong> keine </strong> Rolle. Bitte kontaktieren Sie ihre Manager um von ihm eine Rolle zugewisen zu bekommen",
    "STR_SHOW_OPTIONS": "Optionen anzeigen",
    "STR_SHOW_PROGRESS": "Fortschritt anzeigen:",
    "STR_SAVE": "Speichern",
    "STR_CANCEL": "Abbrechen",
    "STR_DELETE": "Löschen"
});
