/*
  resources.js
  Language: de-de
*/
define({
    "STR_LEARNING_RESOURCES": "Lernmittel",
    "STR_WIDGET_TO_MANAGE_DOCUMENTS_AND": "Widget um Dokumente und Experten zu verwalten.",
    "STR_NO_GOALS_DEFINED": "Keine Ziele festgelegt.",
    "STR_DOCUMENTS": "Dokumente",
    "STR_ADD_NEW_DOCUMENT": "Neues Dokument hinzufügen",
    "STR_EXPERTS": "Experten",
    "STR_ADD_NEW_EXPERT": "Hinzufügen eines neuen Experten",
    "STR_WIDGETS": "Widgets",
    "STR_ADD_NEW_WIDGET": "Hinzufügen eines neuen Widget",
    "STR_IMPORT_FROM_VIEWER": "Import von Viewer",
    "STR_LINK": "Link",
    "STR_PLEASE_ENTER_A_VALID_EMAIL_ADDRESS": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "STR_PROFILE": "Profil",
    "STR_ENTER_EXPERT_PROFILE": "Einsteigen in das Expertenprofil",
    "STR_PHONE_NUMBER": "Telefonnummer",
    "STR_ENTER_PHONE_NUMBER": "Telefonnummer eingeben",
    "STR_ADDRESS": "Adresse  ",
    "STR_ENTER_ADDRESS": "Adresse eingeben",
    "STR_WEBSITE": "Website",
    "STR_ENTER_WEBSITE_URL": "Website URL eingeben",
    "STR_ENTER_SKYPE_ID": "Skype ID eingeben",
    "STR_EDIT_DOCUMENT": "Dokument bearbeiten",
    "STR_UPDATE": "Aktualisierung",
    "STR_EDIT_EXPERT_INFORMATION": "Bearbeiten Sie Experten Informationen",
    "STR_CONTACT_INFORMATIONS": "Kontakt Informationen",
    "STR_EDIT_WIDGET_INFORMATION": "Bearbeiten Widget Informationen",
    "STR_DO_YOU_WANT_TO_DELETE_DOCUMENT": "Wollen Sie wirklich dieses Dokument löschen?",
    "STR_DO_YOU_WANT_TO_DELETE_EXPERT": "Wollen Sie {{Expert.name}} wirklich löschen ?",
    "STR_DO_YOU_WANT_TO_DELETE_WIDGET": "Wollen Sie {{Widget.name}} wirklich löschen ?",
    "STR_CONTACT_INFORMATION_OF": "Kontaktdaten von {{Expert.name}}",
    "STR_INFORMATION_OF": "Informationen zu {{Widget.name}}",
    "STR_LEARNING_RESOURCES_HELP": "Lernressourcen Hilfe",
    "STR_IN_THE_LEARNING_RESOURCES_WIDGET": "<li> Im <em> Lernmittel </ em> Widget können Sie neue Dokumente, Experten und Widgets, überprüfen oder  hinzufügen, die dem Ziel und Lern Indikatoren zugeordnet sind. </ li> <li> Um die Liste der Lern Indikatoren zu sehen die dem Ziel zugeordnet sind, klicken Sie auf den Namen. </ li> <li> Um die Liste der Dokumente zu sehen die einem bestimmten Lernindikator zugeordnet sind klicken Sie auf seinen Namen. </ li> <li> Um die Liste der Experten zu sehen die einem bestimmten Lernindikator sind klicken Sie auf seinen Namen. </ li> <li> Um die Liste der Widgets zu sehen die einem bestimmten Lernindikator zugeordnet sind klicken Sie auf seinen Namen. </ li> <li> Um ein neues Dokument hinzufügen klicken Sie auf <em> neues Dokument hinzufügen <em /> Menüpunkt. In der <em> neues Dokument hinzufügen </ em> Ansicht können Sie Name, Beschreibung und URL vom <em> Boost Viewer </ em> Widget importieren oder es in den entsprechenden Textfelder eingeben. Klicken Sie auf den <em> Speichern </ em> Button, um die Änderungen zu speichern. </ Li> <li> Um neue Experten hinzuzufügen, klicken Sie auf den <em> neuen Experten hinzufügen </ em> Menüpunkt.",
    "STR_IN_THE_ADD_A_NEW_EXPERT_ENTER": "<li> In der <em> einen neuen Experten hinzufügen </ em> Ansicht geben Sie die Kontaktinformationen  des Experten in die entsprechenden Textfelder ein. </ li> <li> Klicken Sie auf den <em> Speichern </ em>, um Änderungen zu speichern. </ li> </ ul> <li> Um ein neues Widget hinzuzufügen klicken Sie auf den <em> Neues Widget hinzufügen</ em> Menüpunkt. <ul style = \"padding: 10px;\">. <li> In der <em> Hinzufügen eines neuen Widget </ em> Ansicht geben Sie den Widget Namen und seine URL-Adresse in die entsprechenden Textfelder En </ li> <li> Klicken Sie auf <em> speichern </ em>, um die Änderungen zu speichern. </ li> </ ul> <li> Um Experten oder Widget-Informationen zu sehen, klicken Sie auf das <button class = 'btn btn btn-default-sm \"> <span class = 'glyphicon glyphicon-Augen-offen \"> </ span> </ button> Icon. </ li>",
    "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Sorry, die Lizenz für BOOST wurde nicht akzeptiert",
    "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Bevor Sie fortfahren müssen Sie zuerst das BOOST Willkommen Widget starten und die Endbenutzer-Lizenzvereinbarung akzeptieren.",
    "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Sorry, Sie haben keine Rechte auf dieses Widget zugreifen",
    "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Bitte kontaktieren Sie Ihre Manager oder Administrator bevor Sie fortfahren",
    "STR_CLOSE": "Schließen",
    "STR_NAME": "Name",
    "STR_SAVE": "Speichern",
    "STR_DESCRIPTION": "Beschreibung",
    "STR_NAME_MUST_NOT_BE_EMPTY": "Name darf nicht leer sein.",
    "STR_PROFILE": "Profil",
    "STR_PHONE_NUMBER": "Telefonnummer",
    "STR_ADDRESS": "Adresse  ",
    "STR_WEBSITE": "Website",
    "STR_ENTER_WEBSITE_URL": "Website URL eingeben",
    "STR_EMPLOYEE_ASSIGN_DOCUMENT": "Dokument welchem Mitarbeiter zuweisen",
    "STR_ALL_EMPLOYEES": "Alle Mitarbeiter",
    "STR_ENTER_NAME": "Name eingeben",
    "STR_ENTER_DESCRIPTION": "Beschreibung eingeben",
    "STR_ENTER_URL": "URL eingeben",
    "STR_IS_PRIVATE": "Ist privat",
    "STR_ADD_NEW_EXPERT": "Hinzufügen eines neuen Experten",
    "STR_ENTER_URL_WIDGET": "Widget-URL eingeben",
    "STR_ENTER_EMAIL_ADDRESS": "Email-Adresse eingeben"
});
