/*
  bcn_management.js
  Language: fr-fr
*/
define({
    "STR_BUSINESS_GOALS": "Objectifs de développement",
    "STR_OVERALL_GOALS_VIEW": "Vue d'ensemble des objectifs",
    "STR_RETURN_TO_MANAGER_VIEW": "Retourner à la vue de manager",
    "STR_ADD_A_NEW_GOAL": "Ajouter un nouvel objectif",
    "STR_LOADING_GOALS": "Chargement des objectifs...",
    "STR_BUSINESS_GOALS_HELP": "Aide sur les objectifs de développement",
    "STR_BUSINESS_GOALS_WIDGET_WAS_CREATED": "Le widget des objectifs de développement a été créé pour aider le manager à organiser ses objectifs. Dans ce widget, le manager peut définir des objectifs, éditer, effacer et ajouter des indicateurs d'apprentissage et assigner des priorités aux objectifs.",
    "STR_TO_ADD_NEW_BUSINESS_GOAL_CLICK": "Pour ajouter un nouvel objectif de développement, cliquez sur l'icone <button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-plus\"></span></button>. Dans la nouvelle vue entrez un <em>Nom</em>, une <em>Description</em> et choississez une <em>Priorité</em> pour cet objectif. Pour ajouter un nouvel <em>Indicateur d'apprentissage</em> cliquez sur l'icone <button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-flag\" style=\"margin-right:5px;\"></span><span class=\"glyphicon glyphicon-plus\"></span></button>.",
    "STR_TO_SEE_OVERALL_PROGRESS_OF_ALL": "Pour voir les progrès des tous les employés, cliquez sur le bouton <button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button>. Le graphique sera affiché dans le widget Progrès des apprentissages.",
    "STR_TO_EDIT_GOAL_CLICK_ON_ICON": "Pour éditer un objectifs, cliquez sur le bouton <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-edit\"></span></button>.",
    "STR_TO_DELETE_GOAL_CLICK_ON_ICON": "Pour supprimer un objectif, cliquez sur le bouton <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-trash\"></span></button>.",
    "STR_TO_MONITOR_THE_LEARNING_PROGRESS": "Pour suivre la progression de chaque employé, allez dans le widget <em>Progrès de l'apprentissage</em> et cliquez sur l'icone <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button>.",
    "STR_IN_THIS_WIDGET_YOU_CAN_MONITOR": "Dans ce widget vous pouvez suivre les objectifs assignés et leurs dates limites. Cliquez sur l'icone <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> pour voir les progrès concernant cet objectif.",
    "STR_SHOW_OPTIONS": "Montrer les options",
    "STR_EDIT": "Editer :",
    "STR_DELETE_COLONS": "Effacer :",
    "STR_SHOW_PROGRESS": "Montrer la progression :",
    "STR_DAYS_BEFORE_THE_DEADLINE": "Jours restants avant la date limite :",
    "STR_20_COMPLETE": "20 % complété",
    "STR_DESCRIPTION": "Description",
    "STR_PRIORITY": "Priorité",
    "STR_LEARNING_INDICATORS": "Objectifs d'apprentissage",
    "STR_SAVE": "Enregistrer",
    "STR_EDIT_GOAL": "Editer l'objectif",
    "STR_DO_YOU_REALLY_WANT_TO_DELETE": "Voulez-vous vraiment effacer ?",
    "STR_CANCEL": "Annuler",
    "STR_DELETE": "Effacer",
    "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Désolé, la licence de BOOST n'a pas été acceptée",
    "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Avant de commencer vous devez lancer le widget de bienvenue et accepter la licence d'utilisation",
    "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Désolé, vous n'avez pas les droits d'accès à ce widget",
    "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Avant de continuer, merci de contacter votre manager ou administrateur",
    "STR_SHOW_HELP": "Montrer l'aide",
    "STR_YOU_HAVE_NO_ROLE": "Vous n'avez aucun « role » pour l'instant. Merci de bien vouloir contacter votre manager afin qu'il vous en attribue un.",
    "STR_CLOSE": "Fermer",
    "STR_SHOW_PROGRESS": "Montrer la progression :",
    "STR_NAME": "Nom",
    "STR_WIDTH": "largeur :",
    "STR_ENTER_NAME": "Entrez le nom",
    "STR_ENTER_DESCRIPTION": "Entrez la description",
    "STR_ENTER_LI_NAME": "Entrez le nom de l'indicateur d'apprentissage"
});
