/*
  employee.js
  Language: fr-fr
*/
define({
    "STR_BUSINESS_EMPLOYEES": "Employés",
    "STR_MANAGE_YOUR_EMPLOYEES_AND_ASSIGN": "Gérer les employés et assigner des objectifs d'apprentissage.",
    "STR_PLEASE_WAIT_WHILE_THE_EMPLOYEES": "Merci de patienter le temps que les changements soient effectifs.",
    "STR_OVERALL_EMPLOYEE_VIEW": "Vue d'ensemble des employés",
    "STR_LOADING_EMPLOYEE_DATA": "Chargement des données des employés",
    "STR_ASSIGN_GOALS": "Assigner des objectifs :",
    "STR_SEND_EMAIL": "Envoyer un courriel :",
    "STR_SHOW_DEADLINES": "Montrer les dates limites :",
    "STR_NAME_MUST_NOT_BE_EMPTY": "Le nom ne doit pas être vide.",
    "STR_EMAIL": "Courriel",
    "STR_ENTER_EMAIL": "Entrez un courriel",
    "STR_PLEASE_ENTER_A_VALID_EMAIL_ADRESS": "Merci d'entrer un courriel valide.",
    "STR_VIEW/UPDATE_EMPLOYEE": "Voir/modifier l'employé",
    "STR_ADD_NEW_EMPLOYEE": "Ajouter un nouvel employé",
    "STR_RELEVANT": "Pertinent",
    "STR_START_DATE": "Date de début",
    "STR_END_DATE": "Date de fin",
    "STR_START_LEVEL": "Niveau de départ",
    "STR_CURRENT_LEVEL": "Niveau actuel",
    "STR_END_LEVEL": "Niveau final",
    "STR_DO_YOU_WANT_TO_DELETE_EMPLOYEE": "Voulez-vous vraiment effacer l'employé {{employee.name}} ?",
    "STR_BUSINESS_EMPLOYEES_HELP": "Aide sur les employés",
    "STR_IN_THE_BUSINESS_EMPLOYEES_WIDGET": "Dans le widget des employés vous pouvez assigner des objectifs, régler leurs niveaux d'apprentissage et spécifier des dates limites.",
    "STR_TO_SEE_MORE_OPTIONS_CLICK_ON": "Pour voir plus d'options, cliquez sur l'icône <button type=\"button\" class=\"btn btn-default btn-sm dropdown-toggle\"><em class=\"fa fa-cogs\"></em><span class=\"caret\"></span></button>.",
    "STR_TO_ASSIGN_GOALS_TO_EMPLOYEE_AND": "Pour assigner des objevtifs aux employés et choisir leurs niveaux d'apprentissage, cliquez sur l'icône <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-flag\" style=\"margin-right:5px;\"></span></button> icon. Dans la nouvelle fenêtre, cochez les objectifs adequat pour cet employé.",
    "STR_CHECK_IN_RELEVANT_LEARNING_INDICATORS": "Passez en revue les indicateurs d'apprentissage adequat et définissez les niveaux d'apprentissage pour cet employé en cliquant sur le nom de l'objectif et en sélectionnant le niveau de départ, le niveau actuel et le niveau de fin.",
    "STR_CHOOSE_START_AND_END_DATES_FOR": "Choisir la date de début et de fin pour les indicateurs d'apprentissage.",
    "STR_DESCRIPTIONS_OF_LEARNING_LEVELS": "Descriptions des niveaux d'apprentissage :",
    "STR_LEVEL_0_I_HAVE_NOT_STARTED_TO": "<li><strong>Niveau 0:</strong> Je n'ai pas commencé à aborder les compétences/connaissances requises pour cet indicateur.</li><li><strong>Niveau 1:</strong> Je n'ai commencé d'aborder les compétences/connaissances pour cet indicateur, mais j'ai besoin de plus de temps/d'aide pour faire des progrès.</li><li><strong>Niveau 2:</strong> Je sens que j'ai acquis des compétences/connaissances et je suis conscient des progrès que j'ai fait en ce qui concerne cet indicateur, mais je pense que j'ai besoin d'en savoir plus avant que je puisse mettre en pratique.</li><li><strong>Niveau 3:</strong> Je sens que j'ai acquis des compétences/connaissances importantes pour mon emploi actuel et j'ai commencé à mettre en pratique.</li><li><strong>Niveau 4:</strong> Je sens que j'ai acquis une connaissance approfondie de ces compétences pour mon emploi actuel, mais pour le développement futur au sein de l'entreprise je reconnais que je peux développer davantage.</li><li><strong>Niveau 5:</strong> Je me sens assez confiant dans l'utilisation de ces compétences et ces connaissances pour que je puisse aider quelques collègues.</li>",
    "STR_TO_MONITOR_THE_LEARNING_EMPLOYEE": "Pour suivre les progrès d'apprentissage d'un employé, consultez le widget <em>Progression de l'apprentissage</em> et cliquez sur l'icone <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats tooltip-showGoalProgress\" data-placement=\"left\" data-toggle=\"tooltip\" data-original-title=\"Voir l'avancement de l'apprentissage\"></span></button>.",
    "STR_TO_SEND_EMAIL_TO_THE_EMPLOYEES": "Pour envoyer un courriel aux employés, cliquez sur l'icone <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-envelope\" style=\"margin-right:5px;\"></span></button>. Une fenêtre surgissante s'ouvrira.",
    "STR_IN_THIS_WIDGET_YOU_CAN_SEE_YOUR": "Dans ce widget vous pouvez voir les détails de votre profil. Cliquez sur l'icone <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> pour voir votre progression.",
    "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Désolé, la licence de BOOST n'a pas été acceptée",
    "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Avant de commencer vous devez lancer le widget de bienvenue et accepter la licence d'utilisation",
    "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Désolé, vous n'avez pas les droits d'accès à ce widget",
    "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Avant de continuer, merci de contacter votre manager ou administrateur",
    "STR_CLOSE": "Fermer",
    "STR_SHOW_HELP": "Montrer l'aide",
    "STR_SHOW_PROGRESS": "Montrer la progression :",
    "STR_YOU_HAVE_NO_ROLE": "Vous n'avez aucun « role » pour l'instant. Merci de bien vouloir contacter votre manager afin qu'il vous en attribue un.",
    "STR_SHOW_OPTIONS": "Montrer les options",
    "STR_SHOW_PROGRESS": "Montrer la progression :",
    "STR_SAVE": "Enregistrer",
    "STR_CANCEL": "Annuler",
    "STR_DELETE": "Effacer"
});
