/*
  bcn_management.js
  Language: el-el
*/
define({
    "STR_BUSINESS_GOALS": "Επιχειρηματικοί στόχοι",
    "STR_OVERALL_GOALS_VIEW": "Συνολική Επισκόπηση Στόχων",
    "STR_RETURN_TO_MANAGER_VIEW": "Επιστροφή την όψη του Μάνατζερ",
    "STR_ADD_A_NEW_GOAL": "Προσθήκη νέου στόχου",
    "STR_LOADING_GOALS": "Φόρτωση στόχων ...",
    "STR_BUSINESS_GOALS_HELP": "Βοήθεια Επιχειρηματικών Στόχων",
    "STR_BUSINESS_GOALS_WIDGET_WAS_CREATED": "Το widget Επιχειρηματικών Στόχων δημιουργήθηκε για να βοηθήσει τον μάνατζερ να οργανώσει τους επιχειρηματικούς στόχους. Σε αυτό το widget ο μάνατζερ μπορεί να προσδιορίσει τους στόχους, να επεξεργαστεί, να διαγράψει και να προσθέσει εκπαιδευτικούς δείκτες, να ορίσει προτεραιότητα στους στόχους.",
    "STR_TO_ADD_NEW_BUSINESS_GOAL_CLICK": "Για να προσθέσετε νέο στόχο κάντε κλικ στο εικονίδιο <button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-plus\"></span></button> . Στην νέα όψη εισάγετε <em>Όνομα</em>, <em>Περιγραφή</em> και επιλέξτε <em>Προτεραιότητα</em> για τον στόχο σας. Για να προσθέσετε νέο <em>Εκπαιδευτικό Δείκτη</em> κάντε κλικ στο εικονίδιο <button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-flag\" style=\"margin-right:5px;\"></span><span class=\"glyphicon glyphicon-plus\"></span></button>.",
    "STR_TO_SEE_OVERALL_PROGRESS_OF_ALL": "Για να δείτε την συνολική πρόοδο όλων των εργαζομένων κάνει κλικ στο εικονίδιο <button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button>. Το γράφημα θα εμφανιστεί στο widget Εκπαιδευτική Πρόοδος.",
    "STR_TO_EDIT_GOAL_CLICK_ON_ICON": "Για να επεξεργαστείτε έναν στόχο κάντε κλικ στο εικονίδιο <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-edit\"></span></button> .",
    "STR_TO_DELETE_GOAL_CLICK_ON_ICON": "Για να διαγράψετε έναν στόχο κάντε κλικ στο εικονίδιο <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-trash\"></span></button>.",
    "STR_TO_MONITOR_THE_LEARNING_PROGRESS": "Για να επιβλέπετε την εκπαιδευτική πρόοδο του κάθε εργαζόμενου πηγαίνετε στο widget <em>Εκπαιδευτική Πρόοδος</em> και πατήστε στο εικονίδιο <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button>.",
    "STR_IN_THIS_WIDGET_YOU_CAN_MONITOR": "Σε αυτό το widget μπορείτε να δείτε τους στόχους και τις προθεσμιες που έχουν οριστεί. Κάντε κλικ στο εικονίδιο <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> για να δείτε την συνολική πρόοδο σε αυτόν τον στόχο στο widget Εκπαιδευτικής Προόδου.",
    "STR_SHOW_OPTIONS": "Εμφάνιση Επιλογών",
    "STR_EDIT": "Επεξεργασία:",
    "STR_DELETE_COLONS": "Διαγραφή:",
    "STR_SHOW_PROGRESS": "Εμφάνιση Προόδου:",
    "STR_DAYS_BEFORE_THE_DEADLINE": "Ημέρες μέχρι την προθεσμία:",
    "STR_20_COMPLETE": "20% Ολοκληρωμένο",
    "STR_DESCRIPTION": "Περιγραφή",
    "STR_PRIORITY": "Προτεραιότητα",
    "STR_LEARNING_INDICATORS": "Εκπαιδευτικοί Δείκτες",
    "STR_SAVE": "Αποθήκευση ",
    "STR_EDIT_GOAL": "Επεξεργασία Στόχου",
    "STR_DO_YOU_REALLY_WANT_TO_DELETE": "Είστε σίγουροι ότι θέλετε να το διαγράψετε",
    "STR_CANCEL": "Ακύρωση",
    "STR_DELETE": "Διαγραφή",
    "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Λυπούμαστε, η άδεια χρήσης για το BOOST δεν έγινε δεκτή",
    "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Πριν προχωρήσετε θα πρέπει πρώτα να ξεκινήσει το widget καλωσορίσματος του Boost και να αποδεχτείτε την Άδεια Χρήσης Τελικού Χρήστη",
    "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Λυπούμαστε, δεν έχετε δικαίωμα πρόσβασης σε αυτό το widget",
    "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Πριν προχωρήσετε, παρακαλούμε επικοινωνήστε με τον μάνατζερ ή το διαχειριστή σας",
    "STR_SHOW_HELP": "Εμφάνιση Βοήθειας",
    "STR_YOU_HAVE_NO_ROLE": "Δεν έχετε <strong>ΚΑΝΕΝΑΝ</strong> ρόλο τώρα. Παρακαλώ, επικοινωνήστε με τον Μάνατζερ για να σας αναθέσει κάποιον ρόλο",
    "STR_CLOSE": "Κλείσιμο",
    "STR_SHOW_PROGRESS": "Εμφάνιση Προόδου:",
    "STR_NAME": "Όνομα",
    "STR_WIDTH": "εύρος:",
    "STR_ENTER_NAME": "Εισαγωγή ονόματος",
    "STR_ENTER_DESCRIPTION": "Εισαγωγή περιγραφής",
    "STR_ENTER_LI_NAME": "Εισαγωγή ονόματος εκπαιδευτικού δείκτη"
});
