/*
  resources.js
  Language: el-el
*/
define({
    "STR_LEARNING_RESOURCES": "Εκπαιδευτικές Πηγές",
    "STR_WIDGET_TO_MANAGE_DOCUMENTS_AND": "Widget για την διαχείριση Αρχείων και Εμπειρογνωμόνων.",
    "STR_NO_GOALS_DEFINED": "Δεν έχουν καθοριστεί στόχοι.",
    "STR_DOCUMENTS": "Αρχεία",
    "STR_ADD_NEW_DOCUMENT": "Προσθήκη νέου αρχείου",
    "STR_EXPERTS": "Εμπειρογνώμονες",
    "STR_ADD_NEW_EXPERT": "Προσθήκη νέου εμπειρογνώμονα",
    "STR_WIDGETS": "Widgets",
    "STR_ADD_NEW_WIDGET": "Προσθήκη νέου widget",
    "STR_IMPORT_FROM_VIEWER": "Εισαγωγή από το Πρόγραμμα Προβολής",
    "STR_LINK": "Σύνδεσμος",
    "STR_PLEASE_ENTER_A_VALID_EMAIL_ADDRESS": "Παρακαλώ εισάγετε μια έγγυρη διεύθυνση email.",
    "STR_PROFILE": "Προφίλ",
    "STR_ENTER_EXPERT_PROFILE": "Εισαγωγή Προφίλ Εμπειρογνώμονα",
    "STR_PHONE_NUMBER": "Αριθμός Τηλεφώνου",
    "STR_ENTER_PHONE_NUMBER": "Εισάγετε Αριθμό Τηλεφώνου",
    "STR_ADDRESS": "Διεύθυνση",
    "STR_ENTER_ADDRESS": "Εισάγετε Διεύθυνση",
    "STR_WEBSITE": "Ιστότοπος",
    "STR_ENTER_WEBSITE_URL": "Εισάγετε διεύθυνση URL του ιστοτόπου",
    "STR_ENTER_SKYPE_ID": "Εισάγετε Skype ID",
    "STR_EDIT_DOCUMENT": "Επεξεργασία Αρχείου",
    "STR_UPDATE": "Ενημέρωση",
    "STR_EDIT_EXPERT_INFORMATION": "Επεξεργασία στοιχείων Εμπειρογνώμονα",
    "STR_CONTACT_INFORMATIONS": "Στοιχεία Επικοινωνίας",
    "STR_EDIT_WIDGET_INFORMATION": "Επεξεργασία στοιχείων widget ",
    "STR_DO_YOU_WANT_TO_DELETE_DOCUMENT": "Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το Αρχείο?",
    "STR_DO_YOU_WANT_TO_DELETE_EXPERT": "Είστε σίγουροι ότι θέλετε να διαγράψετε τον {{Expert.name}}?",
    "STR_DO_YOU_WANT_TO_DELETE_WIDGET": "Είστε σίγουροι ότι θέλετε να διαγράψετε το {{Widget.name}}?",
    "STR_CONTACT_INFORMATION_OF": "Στοιχεία Επικοινωνίας του{{Expert.name}}",
    "STR_INFORMATION_OF": "Στοχεία του {{Widget.name}}",
    "STR_LEARNING_RESOURCES_HELP": "Βοήθεια Εκπαιδευτικών Πηγών",
    "STR_IN_THE_LEARNING_RESOURCES_WIDGET": "<li>Στο widget <em>Εκπαιδευτικές Πηγές</em> μπορείτε να ελέγξετε ή να προσθέσετε νέα Αρχεία, εμπειρογνώμονες και widgets σχετικά με τον στόχο και τους εκπαιδευτικούς δείκτες. </li><li>Για να δείτε την λίστα των εκπαιδευτικών δεικτών αναφορικά με έναν στόχο, κάντε κλικ στο όνομα του.</li><li>Για να δείε την λίστα των αρχείων αναφορικά με έναν εκπαιδευτικό δείκτη, κάντε κλικ στο όνομα του.</li><li>Για να δείτε την λίστα των εμπειρογνωμόνων αναφορικά με έναν εκπαιδευτικό δείκτη κάντε κλικ στο όνομα του.</li><li>Για να δείτε την λίστα των widgets αναφορικά  με έναν εκπαιδευτικό δείκτη κάντε κλικ στο όνομα του.</li><li>Για να προσθέσετε ένα νέο Αρχείο κάντε κλικ στο μενού <em>Add new document</em> . Στην όψη <em>Προσθήκη Νέου Αρχείου</em> μπορείτε να εισάγετε όνομα, περιγραφή και url από το widget <em>Πρόγραμμα Προβολής Boost</em> ή να τα προσθέσετε στα πεδία κειμένου. Κάντε κλικ στο κουμπί <em>Αποθήκευση</em> για να αποθηκεύσετε τις αλλαγές.</li><li>Για να προσθέσετε νέο εμπειρογνώμονα κάντε κλικ στο μενού <em>Προσθήκη Νέου Εμπειρογνώμονα</em>.",
    "STR_IN_THE_ADD_A_NEW_EXPERT_ENTER": "<li>Στο <em>Προσθήκη νέου εμπειρογνώμονα</em> εισάγετε τα στοιχεία επικοινωνίας του εμπειρογνώμονα στα αντίστοιχα πλαίσια κειμένου.</li><li>Κάντε κλικ στο κουμπί <em>Αποθήκευση</em> για να αποθηκεύσετε τις αλλαγές.</li></ul><li>Για να προσθέσετε νέο widget κάντε κλικ στο μενού <em>Προσθήκη νέου widget</em> . <ul style=\"padding: 10px;\"><li>Στο <em>Προσθήκη Νέου Widget</em> εισάγετε το όνομα του νέου widget και την διεύθυνση Url στα αντίστοιχα πλαίσια κειμένου.</li><li>κάντε κλικ στο κουμπί <em>Αποθήκευση</em> για να αποθηκεύσετε τις αλλαγές.</li></ul><li>Για να δείτε τα στιχεία του εμπειρογνώμονα ή του widget, κάντε κλικ στο εικονίδιο <button class='btn btn-default btn-sm'><span class='glyphicon glyphicon-eye-open'></span></button> .</li>",
    "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Λυπούμαστε, η άδεια χρήσης για το BOOST δεν έγινε δεκτή",
    "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Πριν προχωρήσετε θα πρέπει πρώτα να ξεκινήσει το widget καλωσορίσματος του Boost και να αποδεχτείτε την Άδεια Χρήσης Τελικού Χρήστη",
    "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Λυπούμαστε, δεν έχετε δικαίωμα πρόσβασης σε αυτό το widget",
    "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Πριν προχωρήσετε, παρακαλούμε επικοινωνήστε με τον μάνατζερ ή το διαχειριστή σας",
    "STR_CLOSE": "Κλείσιμο",
    "STR_NAME": "Όνομα",
    "STR_SAVE": "Αποθήκευση ",
    "STR_DESCRIPTION": "Περιγραφή",
    "STR_NAME_MUST_NOT_BE_EMPTY": "Το όνομα δεν πρέπει να είναι κενό.",
    "STR_PROFILE": "Προφίλ",
    "STR_PHONE_NUMBER": "Αριθμός Τηλεφώνου",
    "STR_ADDRESS": "Διεύθυνση",
    "STR_WEBSITE": "Ιστότοπος",
    "STR_ENTER_WEBSITE_URL": "Εισάγετε διεύθυνση URL του ιστοτόπου",
    "STR_EMPLOYEE_ASSIGN_DOCUMENT": "Εργαζόμενος για ανάθεση εγγράφου",
    "STR_ALL_EMPLOYEES": "Όλοι οι εργαζόμενοι",
    "STR_ENTER_NAME": "Εισαγωγή ονόματος",
    "STR_ENTER_DESCRIPTION": "Εισαγωγή περιγραφής",
    "STR_ENTER_URL": "Εισαγωγή διεύθυνσης url",
    "STR_IS_PRIVATE": "Είναι ιδιωτικό",
    "STR_ADD_NEW_EXPERT": "Προσθήκη νέου εμπειρογνώμονα",
    "STR_ENTER_URL_WIDGET": "Εισαγωγή διεύθυνσης url ή widget",
    "STR_ENTER_EMAIL_ADDRESS": "Εισαγωγή email"
});
