define({
    "root" : {
        "STR_BUSINESS_GOALS": "Business goals",
        "STR_OVERALL_GOALS_VIEW": "Overall Goals View",
        "STR_RETURN_TO_MANAGER_VIEW": "Return to Manager View",
        "STR_ADD_A_NEW_GOAL": "Add a new goal",
        "STR_LOADING_GOALS": "Loading goals...",
        "STR_BUSINESS_GOALS_HELP": "Business Goals Help",
        "STR_BUSINESS_GOALS_WIDGET_WAS_CREATED": "Business Goals widget was created to help manager organize business goals. In this widget manager can define goals, edit, delete and add learning indicators, assign priorities to goals.",
        "STR_TO_ADD_NEW_BUSINESS_GOAL_CLICK": "To add new business goal click on <button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-plus\"></span></button> icon. In the new view enter <em>Name</em>, <em>Description</em> and choose <em>Priority</em> for your goal. To add new <em>Learning Indicator</em> click on <button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-flag\" style=\"margin-right:5px;\"></span><span class=\"glyphicon glyphicon-plus\"></span></button> icon.",
        "STR_TO_SEE_OVERALL_PROGRESS_OF_ALL": "To see overall progress of all employees click on <button type=\"button\" class=\"btn btn-primary btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> icon. The graph will be shown in the Learning Progress widget.",
        "STR_TO_EDIT_GOAL_CLICK_ON_ICON": "To edit goal click on <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-edit\"></span></button> icon.",
        "STR_TO_DELETE_GOAL_CLICK_ON_ICON": "To delete goal click on <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-trash\"></span></button> icon.",
        "STR_TO_MONITOR_THE_LEARNING_PROGRESS": "To monitor the learning progress of each employee straight forward in <em>Learning Progress</em> widget click on <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> icon.",
        "STR_IN_THIS_WIDGET_YOU_CAN_MONITOR": "In this widget you can monitor assigned goals and timelines. Click on <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> icon to see progress over this goal in the Learning Progress widget.",
        "STR_SHOW_OPTIONS": "Show Options",
        "STR_EDIT": "Edit: ",
        "STR_DELETE_COLONS": "Delete: ",
        "STR_SHOW_PROGRESS": "Show Progress: ",
        "STR_DAYS_BEFORE_THE_DEADLINE": "Days before the deadline: ",
        "STR_20_COMPLETE": "20% Complete",
        "STR_DESCRIPTION": "Description",
        "STR_PRIORITY": "Priority",
        "STR_LEARNING_INDICATORS": "Learning indicators",
        "STR_SAVE": "Save",
        "STR_EDIT_GOAL": "Edit goal",
        "STR_DO_YOU_REALLY_WANT_TO_DELETE": "Do you really want to delete ",
        "STR_CANCEL": "Cancel",
        "STR_DELETE": "Delete",
        "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Sorry, the license for BOOST was not accepted",
        "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Before proceeding you must first launch BOOST Welcome Widget and accept the End User License Agreement",
        "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Sorry, you do not have rights to access this widget",
        "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Before proceeding please contact your manager or administrator",
        "STR_SHOW_HELP": "Show Help",
        "STR_YOU_HAVE_NO_ROLE": "You have <strong>NO</strong> roles now. Please, contact Manager to assign roles for you",
        "STR_CLOSE": "Close",
        "STR_SHOW_PROGRESS": "Show Progress: ",
        "STR_NAME": "Name",
        "STR_WIDTH": "width: ",
        "STR_ENTER_NAME": "Enter Name",
        "STR_ENTER_DESCRIPTION": "Enter description",
        "STR_ENTER_LI_NAME": "Enter learning indicator name"
    },
    "de-de" : true,
    "cz-cz" : true,
    "el-el" : true,
    "fr-fr" : true
});