define({
    "root" : {
        "STR_BUSINESS_EMPLOYEES": "Business Employees",
        "STR_MANAGE_YOUR_EMPLOYEES_AND_ASSIGN": "Manage your employees and assign learning goals to them.",
        "STR_PLEASE_WAIT_WHILE_THE_EMPLOYEES": "Please wait while the employees are updated to reflect these changes.",
        "STR_OVERALL_EMPLOYEE_VIEW": "Overall Employee View",
        "STR_LOADING_EMPLOYEE_DATA": "Loading employee data...",
        "STR_ASSIGN_GOALS": "Assign goals: ",
        "STR_SEND_EMAIL": "Send email: ",
        "STR_SHOW_DEADLINES": "Show Deadlines: ",
        "STR_NAME_MUST_NOT_BE_EMPTY": "Name must not be empty.",
        "STR_EMAIL": "Email",
        "STR_ENTER_EMAIL": "Enter email",
        "STR_PLEASE_ENTER_A_VALID_EMAIL_ADRESS": "Please enter a valid email adress.",
        "STR_VIEW/UPDATE_EMPLOYEE": "View/Update Employee",
        "STR_ADD_NEW_EMPLOYEE": "Add new Employee",
        "STR_RELEVANT": "Relevant",
        "STR_START_DATE": "Start Date",
        "STR_END_DATE": "End Date",
        "STR_START_LEVEL": "Start level:",
        "STR_CURRENT_LEVEL": "Current level:",
        "STR_END_LEVEL": "End level:",
        "STR_DO_YOU_WANT_TO_DELETE_EMPLOYEE": "Do you really want to delete {{employee.name}} as an employee?",
        "STR_BUSINESS_EMPLOYEES_HELP": "Business Employees Help",
        "STR_IN_THE_BUSINESS_EMPLOYEES_WIDGET": "In the Business Employees widget you can assign goals to the employees, adjust their learning levels and specify deadlines for them.",
        "STR_TO_SEE_MORE_OPTIONS_CLICK_ON": "To see more options click on <button type=\"button\" class=\"btn btn-default btn-sm dropdown-toggle\"><i class=\"fa fa-cogs\"></em><span class=\"caret\"></span></button> icon.",
        "STR_TO_ASSIGN_GOALS_TO_EMPLOYEE_AND": "To assign goals to employee and define learning levels click on <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-flag\" style=\"margin-right:5px;\"></span></button> icon. In the new view check in relevant goals for this employee.",
        "STR_CHECK_IN_RELEVANT_LEARNING_INDICATORS": "Review relevant learning indicators and define learning levels for this employee by clicking on the goal name and selecting start, current and end level accordingly.",
        "STR_CHOOSE_START_AND_END_DATES_FOR": "Choose start and end dates for the learning indicators.",
        "STR_DESCRIPTIONS_OF_LEARNING_LEVELS": "Descriptions of learning levels:",
        "STR_LEVEL_0_I_HAVE_NOT_STARTED_TO": "<li><strong>Level 0:</strong> I have not started to address the skills / knowledge required for this indicator.</li><li><strong>Level 1:</strong> I have started to try to address the skills / knowledge for this indicator but need more time / support to make progress.</li><li><strong>Level 2:</strong> I feel that I have acquired some skills / knowledge and am aware of the progress I have made with regards to this indicator but feel that I need to learn more before I can put into practice on the job.</li><li><strong>Level 3:</strong> I feel that I have acquired significant skills / knowledge for my current job role and have started   to put into practice on the job.</li><li><strong>Level 4:</strong> I feel that I have acquired significant knowledge of these skills for my current job role but for future development within the company, I recognise that I can develop further.</li><li><strong>Level 5:</strong> I feel confident enough in using these skills and knowledge so that I could support a few colleagues with regard to these?</li>",
        "STR_TO_MONITOR_THE_LEARNING_EMPLOYEE": "To monitor the learning progress of employee go to <em>Learning Progress</em> widget click on <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats tooltip-showGoalProgress\" data-placement=\"left\" data-toggle=\"tooltip\" data-original-title=\"Show Progress: Decor and Furnishing\"></span></button> icon.",
        "STR_TO_SEND_EMAIL_TO_THE_EMPLOYEES": "To send email to the employees click on <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-envelope\" style=\"margin-right:5px;\"></span></button> icon. Pop-up mail window will appear.",
        "STR_IN_THIS_WIDGET_YOU_CAN_SEE_YOUR": "In this widget you can see your profile details. Click on <button class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-stats\"></span></button> icon to see  your overall progress in the Learning Progress widget.",
        "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Sorry, the license for BOOST was not accepted",
        "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Before proceeding you must first launch BOOST Welcome Widget and accept the End User License Agreement",
        "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Sorry, you do not have rights to access this widget",
        "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Before proceeding please contact your manager or administrator",
        "STR_CLOSE": "Close",
        "STR_SHOW_HELP": "Show Help",
        "STR_SHOW_PROGRESS": "Show Progress: ",
        "STR_YOU_HAVE_NO_ROLE": "You have <strong>NO</strong> roles now. Please, contact Manager to assign roles for you",
        "STR_SHOW_OPTIONS": "Show Options",
        "STR_SAVE": "Save",
        "STR_CANCEL": "Cancel",
        "STR_DELETE": "Delete"
    },
    "de-de" : true,
    "cz-cz" : true,
    "el-el" : true,
    "fr-fr" : true
});