define({
    "root" : {
        "STR_LEARNING_RESOURCES": "Learning Resources",
        "STR_WIDGET_TO_MANAGE_DOCUMENTS_AND": "Widget to manage Documents and Experts.",
        "STR_NO_GOALS_DEFINED": "No goals defined.",
        "STR_DOCUMENTS": "Documents",
        "STR_ADD_NEW_DOCUMENT": "Add new document",
        "STR_EXPERTS": "Experts",
        "STR_ADD_NEW_EXPERT": "Add new expert",
        "STR_WIDGETS": "Widgets",
        "STR_ADD_NEW_WIDGET": "Add new widget",
        "STR_IMPORT_FROM_VIEWER": "Import from viewer",
        "STR_LINK": "Link",
        "STR_PLEASE_ENTER_A_VALID_EMAIL_ADDRESS": "Please enter a valid email address.",
        "STR_PROFILE": "Profile",
        "STR_ENTER_EXPERT_PROFILE": "Enter Expert Profile",
        "STR_PHONE_NUMBER": "Phone number",
        "STR_ENTER_PHONE_NUMBER": "Enter Phone number",
        "STR_ADDRESS": "Address",
        "STR_ENTER_ADDRESS": "Enter Address",
        "STR_WEBSITE": "Website",
        "STR_ENTER_WEBSITE_URL": "Enter Website url",
        "STR_ENTER_SKYPE_ID": "Enter Skype ID",
        "STR_EDIT_DOCUMENT": "Edit Document",
        "STR_UPDATE": "Update",
        "STR_EDIT_EXPERT_INFORMATION": "Edit expert information",
        "STR_CONTACT_INFORMATIONS": "Contact Informations",
        "STR_EDIT_WIDGET_INFORMATION": "Edit widget information",
        "STR_DO_YOU_WANT_TO_DELETE_DOCUMENT": "Do you really want to delete this Document?",
        "STR_DO_YOU_WANT_TO_DELETE_EXPERT": "Do you really want to delete",
        "STR_DO_YOU_WANT_TO_DELETE_WIDGET": "Do you really want to delete",
        "STR_CONTACT_INFORMATION_OF": "Contact information of",
        "STR_INFORMATION_OF": "Information of",
        "STR_LEARNING_RESOURCES_HELP": "Learning Resources Help",
        "STR_IN_THE_LEARNING_RESOURCES_WIDGET": "<li>In the <em>Learning Resources</em> widget you can review or add new documents, experts and widgets assigned to the goal and learning indicators. </li><li>To see the list of learning indicators assigned to the goal click on its name.</li><li>To see the list of documents assigned to a particular learning indicator click on its name.</li><li>To see the list of experts assigned to a particular learning indicator click on its name.</li><li>To see the list of widgets assigned to a particular learning indicator click on its name.</li><li>To add new document click on <em>Add new document</em> menu item. In the <em>Add a new Document</em> view you can import name, description and url from the <em>Boost Viewer</em> widget or enter it in appropriate text fields. Click on <em>Save</em> button to save changes.</li><li>To add new expert click on <em>Add new expert</em> menu item. ",
        "STR_IN_THE_ADD_A_NEW_EXPERT_ENTER": "<li>In the <em>Add a new Expert</em> enter the expert contact infotmations in appropriate text fields.</li><li>Click on <em>Save</em> button to save changes.</li></ul><li>To add new widget click on <em>Add new widget</em> menu item. <ul style=\"padding: 10px;\"><li>In the <em>Add a new Widget</em> enter the widget name and its Url address in appropriate text fields.</li><li>Click on <em>Save</em> button to save changes.</li></ul><li>To see expert or widget informations, click on <button class='btn btn-default btn-sm'><span class='glyphicon glyphicon-eye-open'></span></button> icon.</li>",
        "STR_SORRY_THE_LICENSE_FOR_BOOST_WAS": "Sorry, the license for BOOST was not accepted",
        "STR_BEFORE_PROCEEDING_YOU_MUST_FIRST": "Before proceeding you must first launch BOOST Welcome Widget and accept the End User License Agreement",
        "STR_SORRY_YOU_DO_NOT_HAVE_RIGHTS": "Sorry, you do not have rights to access this widget",
        "STR_BEFORE_PROCEEDING_PLEASE_CONTACT": "Before proceeding please contact your manager or administrator",
        "STR_CLOSE": "Close",
        "STR_NAME": "Name",
        "STR_SAVE": "Save",
        "STR_DESCRIPTION": "Description",
        "STR_NAME_MUST_NOT_BE_EMPTY": "Name must not be empty.",
        "STR_PROFILE": "Profile",
        "STR_PHONE_NUMBER": "Phone number",
        "STR_ADDRESS": "Address",
        "STR_WEBSITE": "Website",
        "STR_ENTER_WEBSITE_URL": "Enter Website url",
        "STR_EMPLOYEE_ASSIGN_DOCUMENT": "Employee to Assign Document",
        "STR_ALL_EMPLOYEES": "All Employees",
        "STR_ENTER_NAME": "Enter Name",
        "STR_ENTER_DESCRIPTION": "Enter description",
        "STR_ENTER_URL": "Enter url",
        "STR_IS_PRIVATE": "Is Private",
        "STR_ADD_NEW_EXPERT": "Add new expert",
        "STR_ENTER_URL_WIDGET": "Enter url of widget",
        "STR_ENTER_EMAIL_ADDRESS": "Enter Email Address"
    },
    "de-de" : true,
    "cz-cz" : true,
    "el-el" : true,
    "fr-fr" : true
});
